FROM wyveo/nginx-php-fpm:php80
LABEL devops-xsa.version="1.0"
LABEL maintainer="Jarbson Santana de Jesus"
LABEL devops-xsa.release-date="2023-01-23"
ENV TZ="America/Sao_Paulo"
ENV USER="nginx"

RUN groupmod -g 1003 nginx && usermod -u 1003 -g 1003 nginx && apt-get update && apt-get -y install cron
RUN date
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /usr/share/nginx/
RUN rm -rf /usr/share/nginx/html && rm -f /etc/nginx/nginx.conf && rm -f /etc/nginx/conf.d/default.conf && apt-get -y install php8.0-xdebug

COPY VERSION ./

RUN chmod 0644 /etc/cron.d/xsa-cron && crontab /etc/cron.d/xsa-cron
RUN groupadd -g 998 docker && usermod -aG docker nginx
RUN echo max_input_vars=5000 >> /etc/php/8.0/fpm/php.ini && echo post_max_size=64M >> /etc/php/8.0/fpm/php.ini && echo upload_max_filesize=128M >> /etc/php/8.0/fpm/php.ini

CMD ["sh","-c","cron && /start.sh"]